config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  #get "todos", to: "todos#index"
  # get "todos" , to: "todos#new"
  # post "todos" , to: "todos#create"
  # get "todos/:id", to: "todos#show"
  # get "todos/:id/edit" , to: "todos#edit"
  # put "todos/:id" , to: "todos#update"
  # delete "todos/:id" , to: "todos#destroy"
  get "/" => "home#index", as: :home
  resources :todos
  resources :users
  #get "sigin1", to: "sigin1#new"
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo<ActiveRecord::Base
  validates :todo_text, presence: true
  validates :due_date, presence: true
  
  belongs_to :user
   def due_today?
    due_date=Date.today
   end
    def self.of_user(user)
      all.where(user_id: user.id)
    end
    def to_displayable_string
      display_status = completed ? "[X]" : "[ ]"
      dispaly_date=due_today ? nil : due_date
      "#{id}.#{display_status} #{todo_text} #{display_date}"
    end

    def self.show_list
      all.map{|todo| todo.to_displayable_string}
    end

    def self.overdue
      all.where("due_date < ?", Date.today)
    end

    def self.due_today
      all.where("due_date = ?", Date.today)
    end

    def self.due_later
      all.where("due_date > ?", Date.today)
    end
    
    def self.completed
      all.where(completed: true)
    end
    # def self.add_task(h)
    #   Todo.create!(
    #     toto_text: h[:todo-text],
    #     due_date: Date.today+h[:due_in_days],
    #     completed: false,
    #   )
    # end

    def self.show_list
      puts "My Todo-list\n\n"
      puts "Overdue\n"
      puts overdue.show_list
      puts "\n\n"

      puts "Due Today\n"
      puts due_today.show_list
      puts "\n\n"

      puts "Due later\n"
      puts due_later.show_list
      puts "\n\n"
    end

    def self.mark_as_completed!(id)
      todo=find(id)
      todo.completed=true
      todo.save!
      todo
    end
end

app/models/user.rb
class User < ApplicationRecord
    validates :first_name, presence: true
    validates :email, presence: true
    validates :password, presence: true

    has_secure_password
    has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :ensure_user_logged_in
    
    def ensure_user_logged_in
        unless current_user
            redirect_to "/"
        end
    end

    def current_user
        return @current_user if @current_user

        current_user_id=session[:current_user_id]
        if current_user_id
            @current_user = User.find(current_user_id)
        else
            nil
        end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    skip_before_action :ensure_user_logged_in
    def index
        if current_user
            redirect_to todos_path
        else 
            render "index"
        end
    end
    def new
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 
    skip_before_action :ensure_user_logged_in
    def new
    end
    def create
        user=User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
            session[:current_user_id]=user.id
            #debugger
            redirect_to "/"

       else
        flash[:error]="Your login attempt was invalid. Please retry."
        redirect_to new_sessions_path
       end
    end

    def destroy
        #console.log('------hi-------s')
        session[:current_user_id] = nil
        @current_user = nil
        redirect_to home_path
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController 

    def index
        #render plain: Todo.order(:due_date).map{|todo| todo.to_pleasent_string}.join("\n")
        @todos=Todo.of_user(current_user)
        render "index"
    end

    def new 
    end 

    def create
        todo_text=params[:todo_text]
        due_date=params[:due_date]
        new_todo=Todo.new(
            todo_text: todo_text,
            due_date: due_date,
            completed: false,
            user_id: current_user.id,
        )
        if new_todo.save
            redirect_to todos_path 
        #response_text= "new todo #{new_todo.id}"
        #render plain:  response_text
        else
            flash[:error]= new_todo.errors.full_messages.join(", ")
            redirect_to todos_path
      end
    end

    def show
        id=params[:id]
        todo=Todo.of_user(current_user).find(id)
        render plain: todo.to_pleasent_string
    end

   

    def edit
    end 

    def update
        id=params[:id]
        completed=params[:completed]
        todo=Todo.of_user(current_user).find(id)
        todo.completed=completed
        todo.save!
        redirect_to todos_path
    end
    def destroy
        id=params[:id]
        todo=Todo.of_user(current_user).find(id)
        todo.destroy
        redirect_to todos_path
    end
end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
    skip_before_action :ensure_user_logged_in

    def new
    end

    def create
     user=User.find_by(email: params[:email])
     if user
         flash[:error]="This email is already registered. Please retry."
         redirect_to new_user_path 
     else
         user=User.new(
            first_name: params[:first_name],
            last_name: params[:last_name],
            email: params[:email],
            password: params[:password],
         )
         session[:current_user_id]= user.id
           if user.save
              redirect_to "/" 
        #response_text= "new todo #{new_todo.id}"
        #render plain:  response_text
            else
               flash[:error]= user.errors.full_messages.join(", ")
               redirect_to new_user_path
            end
        end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<p> Welcome to todo app </p>
<p> If you are a new user, <%= link_to "sign up here", new_user_path%></p>
<p> If you are an existing user, <%= link_to "sign in here", new_sessions_path%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <% if @current_user %>
  <p class="UserHeader">
    Welcome <%= @current_user.first_name%>
    <%= button_to "Sign-out", destroy_session_path, method: "delete", class:"UserHeader1"%>
  </p>
  <% end%>
  <% if flash[:error] %>
    <p class="Flash-error">
      <%= flash[:error] %>
    </p>

  <% end %>
    <%= yield %>
  </body>
</html>

app/views/todos/_todo-section.html.erb
<section class="TodoSection">
      <div class="TodoSectionTitle">
         <p class="TodoSectionTitle-text"><%= section_title %> </h2>
         <p class="TodoSectionTitle-remainingCount"><%= todos.completed.count%>/<%= todos.count %> </p>
      </div>
                                <ul>
                                <% todos.each do |todo| %>
                                    <li class="TodoItem"> 
                                        <div class="TodoItem-container">
                                       <%= form_with(url: "/todos/#{todo.id}" , method: "put") do %>
                                            <input class="TodoItem-checkbox" name="completed" type="checkbox" <%= todo.completed ? "checked" : "" %> 
                                            onclick="this.form.submit()" >
                                            
                                        <% end %>
                                            
                                            <%= todo.todo_text %>
                                            <% if show_due_date %>
                                               <%= todo.due_date %>
                                            <% end %>
                                            <a href="javascript:void(0)" class="TodoItem-delete">
                                            <%= form_with(url: "/todos/#{todo.id}" , method: "delete") do %>
                                            <input type="image" src="https://pic.onlinewebfonts.com/svg/img_446501.png" width="12px" class="TodoItem-delete">
                                            <% end %>
                                            </a>
                                        </div>
                                    </li>
                                    <% end %>
                                </ul>
</section>

app/views/todos/index.html.erb
<main class="TodoPageMain">
            <h1 class="TodoPage-title">My Todo-list</h1>
            <%= form_with(url: "/todos" ,method: "post" ,class: "AddTodo") do%>
           <!-- <form class="AddTodo" action="/todos" method="POST" > -->
                <input class="AddTodo-text" type="text" placeholder="What's next?" name="todo_text">
                <input class="AddTodo-date" type="date" name="due_date">
                <input class="AddTodo-button" type="submit" value="Add"> 
            <% end %>
           <!-- </form> -->
            <%= render partial: "todo-section" , locals: {
                section_title: "Overdue",
                todos: @todos.overdue,
                show_due_date: true
                } %>
            <%= render partial: "todo-section" , locals: {
                section_title: "Due Today",
                todos: @todos.due_today,
                show_due_date: false
                } %>
            <%= render partial: "todo-section" , locals: {
                section_title: "Due Later",
                todos: @todos.due_later,
                show_due_date: true
                } %>
</main>

app/views/users/new.html.erb
<p class="NewUsers-title"> Welcome new user! </p>
<section class="UserNew">
<%= form_with url: users_path do |form| %>
<div class="Form-section">
<p class="FormInput-label"> First name:</p>
 <%= form.text_field :first_name, class: "Form-input" %>
 </div>
 <div class="Form-section">
<p class="FormInput-label"> Last name:</p>
 <%= form.text_field :last_name, class: "Form-input"%>
 </div>
 <div class="Form-section">
<p class="FormInput-label"> Email</p>
 <%= form.email_field :email, class: "Form-input"%>
 </div>
 <div class="Form-section">
<p class="FormInput-label"> Password:</p>
 <%= form.password_field :password, class: "Form-input"%>
 </div>
 <div class="Form-section">
 <%= form.submit "Sign-up!", class: "Form-submit"%>
 </div>
 </section>
 
<% end%>